<#
.SYNOPSIS
    Backs up and re-applies LilithMod around a game reinstall.

.DESCRIPTION
    A Steam reinstall deletes the entire game folder, which takes BepInEx, the
    generated interop assemblies, the mod DLL, the config file (holding the user's
    API key) and any authored custom dialogue with it. Only this repo survives.

    Run -Backup BEFORE uninstalling, then -Restore after the reinstall finishes.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\reapply-mod.ps1 -Backup
    powershell -ExecutionPolicy Bypass -File .\reapply-mod.ps1 -Restore
#>
[CmdletBinding()]
param(
    [switch]$Backup,
    [switch]$Restore,
    [string]$GameDir = "D:\SteamLibrary\steamapps\common\The NOexistenceN of Lilith"
)

$ErrorActionPreference = "Stop"

$RepoDir   = $PSScriptRoot
$BackupDir = Join-Path $RepoDir "backup"
$BepInZip  = Join-Path $RepoDir "tools\bepinex785.zip"
$Csproj    = Join-Path $RepoDir "LilithMod\LilithMod.csproj"
$Dotnet    = "C:\Program Files\dotnet\dotnet.exe"

$ConfigRel = "BepInEx\config\LilithMod.cfg"
$CustomRel = "BepInEx\plugins\LilithMod\custom"
$InteropMarker = "BepInEx\interop\Assembly-CSharp.dll"

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Warn($msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Ok($msg)   { Write-Host "  + $msg" -ForegroundColor Green }

function Assert-GameDir {
    if (-not (Test-Path (Join-Path $GameDir "Lilith.exe"))) {
        throw "No Lilith.exe under '$GameDir'. Pass the right path with -GameDir."
    }
}

function Stop-Game {
    $procs = Get-Process -Name "Lilith" -ErrorAction SilentlyContinue
    if (-not $procs) { return }
    Write-Step "Closing the game (it locks LilithMod.dll and blocks the build)"
    $procs | Stop-Process -Force
    # Wait for the handle to actually drop, not just for the kill to be issued.
    for ($i = 0; $i -lt 30; $i++) {
        Start-Sleep -Milliseconds 500
        if (-not (Get-Process -Name "Lilith" -ErrorAction SilentlyContinue)) { break }
    }
    Write-Ok "Game closed."
}

function Invoke-Backup {
    Assert-GameDir

    $cfgSrc    = Join-Path $GameDir $ConfigRel
    $customSrc = Join-Path $GameDir $CustomRel

    if (-not (Test-Path $BackupDir)) { New-Item -ItemType Directory -Path $BackupDir | Out-Null }

    Write-Step "Backing up to $BackupDir"

    if (Test-Path $cfgSrc) {
        Copy-Item $cfgSrc (Join-Path $BackupDir "LilithMod.cfg") -Force
        Write-Ok "LilithMod.cfg (contains your API key - gitignored, never commit it)"
    } else {
        Write-Warn "No LilithMod.cfg found; nothing to preserve. You will re-enter the API key."
    }

    if (Test-Path $customSrc) {
        $dest = Join-Path $BackupDir "custom"
        if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
        Copy-Item $customSrc $dest -Recurse -Force
        $n = (Get-ChildItem $dest -Filter *.json -ErrorAction SilentlyContinue | Measure-Object).Count
        Write-Ok "custom\ ($n dialogue file(s))"
    } else {
        Write-Warn "No custom\ folder found; no authored dialogue to preserve."
    }

    Write-Host ""
    Write-Host "Backup done. Safe to uninstall the game." -ForegroundColor Green
    Write-Host "Afterwards run:  .\reapply-mod.ps1 -Restore"
}

function Invoke-Restore {
    Assert-GameDir
    if (-not (Test-Path $BepInZip)) {
        throw "Missing '$BepInZip'. Re-download BepInEx 6.0.0-be.785 (or newer) x64 IL2CPP from builds.bepinex.dev."
    }

    Stop-Game

    Write-Step "Installing BepInEx into the game folder"
    Expand-Archive -Path $BepInZip -DestinationPath $GameDir -Force
    $doorstopConfig = Join-Path $GameDir "doorstop_config.ini"
    $doorstopText = Get-Content -LiteralPath $doorstopConfig -Raw
    $doorstopText = $doorstopText -replace '(?m)^ignore_disable_switch\s*=\s*false\s*$', 'ignore_disable_switch = true'
    Set-Content -LiteralPath $doorstopConfig -Value $doorstopText -Encoding utf8
    Write-Ok "BepInEx, doorstop and the CoreCLR runtime extracted."

    # Interop assemblies are generated by BepInEx from the CURRENT GameAssembly.dll on
    # first launch. They are what the mod compiles against, so they must exist and must
    # match the installed game version before the build can run.
    $interop = Join-Path $GameDir $InteropMarker
    if (-not (Test-Path $interop)) {
        Write-Step "Generating interop assemblies (first launch - this takes several minutes)"
        $exe = Join-Path $GameDir "Lilith.exe"
        Start-Process -FilePath $exe -WorkingDirectory $GameDir | Out-Null

        $deadline = (Get-Date).AddMinutes(15)
        while (-not (Test-Path $interop)) {
            if ((Get-Date) -gt $deadline) {
                throw "Interop generation timed out. Check BepInEx\LogOutput.log for a metadata-version error."
            }
            Start-Sleep -Seconds 5
        }
        # The marker file appears before the run finishes; let the rest settle.
        Start-Sleep -Seconds 20
        Write-Ok "Interop generated."
        Stop-Game
    } else {
        Write-Ok "Interop already present; skipping first-launch generation."
    }

    Write-Step "Restoring your settings"
    $cfgBak = Join-Path $BackupDir "LilithMod.cfg"
    if (Test-Path $cfgBak) {
        $cfgDest = Join-Path $GameDir $ConfigRel
        New-Item -ItemType Directory -Path (Split-Path $cfgDest) -Force | Out-Null
        Copy-Item $cfgBak $cfgDest -Force
        Write-Ok "LilithMod.cfg restored (API key and hotkey intact)."
    } else {
        Write-Warn "No backed-up config. The mod will write a fresh one; add your ApiKey to it."
    }

    $customBak = Join-Path $BackupDir "custom"
    if (Test-Path $customBak) {
        $customDest = Join-Path $GameDir $CustomRel
        New-Item -ItemType Directory -Path $customDest -Force | Out-Null
        Copy-Item (Join-Path $customBak "*") $customDest -Recurse -Force
        Write-Ok "Custom dialogue restored."
    }

    Write-Step "Building the mod"
    & $Dotnet build $Csproj -c Release
    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Warn "Build failed. If the game updated, its API may have changed -"
        Write-Warn "check the errors against DialogueManager / DialogueNode / DialogueBubbleUI / WindowsNativeAPI."
        exit 1
    }

    Write-Host ""
    Write-Host "Mod re-applied. Launch the game and press F11 to chat." -ForegroundColor Green
    Write-Host "Verify with: BepInEx\LogOutput.log should show [LilithMod] lines."
}

if ($Backup -and $Restore) { throw "Pick one: -Backup or -Restore." }
elseif ($Backup)  { Invoke-Backup }
elseif ($Restore) { Invoke-Restore }
else {
    Write-Host "LilithMod reinstall helper"
    Write-Host ""
    Write-Host "  .\reapply-mod.ps1 -Backup    Run BEFORE uninstalling the game."
    Write-Host "  .\reapply-mod.ps1 -Restore   Run AFTER the reinstall finishes."
    Write-Host ""
    Write-Host "Game dir: $GameDir"
}
